const System = require('systemic')
const confabulous = require('./components/confabulous')
const prepper = require('./components/prepper')
const prepperRequest = require('./components/prepper-request')
const service = require('./components/service')
const server = require('./components/express-server')
const app = require('./components/express-app')
const handlers = require('./components/express-handlers')
const mongo = require('./components/mongo')
const consoleLog = require('./transports/console-log')
const jsonLog = require('./transports/json-log')
const system = new System()
const pkg = require('../package')

module.exports = new System()
    .configure(confabulous())
    .add('transports.console', consoleLog)
    .add('transports.json', jsonLog)
    .add('logger', prepper({ package: pkg })).dependsOn('config', 'transports.console', 'transports.json')
    .add('requestLogger', prepperRequest()).dependsOn('logger', 'app')
    .add('app', app()).dependsOn('config', 'logger')
    .add('mongo', mongo()).dependsOn('config', 'logger')
    .add('service', service()).dependsOn('config', 'app', 'mongo')
    .add('handlers', handlers()).dependsOn('app')
    .add('server', server()).dependsOn('config', 'app', 'service')

