const System = require('systemic')
const confabulous = require('./components/confabulous')
const prepper = require('./components/prepper')
const server = require('./components/express-server')
const app = require('./components/express-app')
const adminRoutes = require('./routes/admin-routes')
const prepperRoutes = require('./routes/prepper-routes')
const mongo = require('./components/mongo')
const consoleLog = require('./transports/console-log')
const jsonLog = require('./transports/json-log')
const pkg = require('../package')
const manifest = require('../manifest')

module.exports = new System()
    .configure(confabulous())
    .add('package', pkg)
    .add('manifest', manifest)
    .add('transports.console', consoleLog)
    .add('transports.json', jsonLog)
    .add('logger', prepper()).dependsOn('package', 'config', 'transports.console', 'transports.json')
    .add('routes.prepper', prepperRoutes()).dependsOn('logger')
    .add('routes.admin', adminRoutes()).dependsOn('manifest')
    .add('app', app()).dependsOn('config', 'logger', 'routes.prepper', 'routes.admin')
    .add('mongo', mongo()).dependsOn('config', 'logger')
    .add('server', server()).dependsOn('config', 'app')

